name: 'Setup'
description: 'Common setup steps for GitHub Actions'
runs:
  using: 'composite'
  steps:
    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.9.0
      with:
        enable-cache: 'true'
    - name: Load devbox via direnv
      uses: HatsuneMiku3939/direnv-action@v1

    - name: Check xdebug config
      shell: bash
      run: |
        if ! php --info | grep 'xdebug.mode => develop => develop'; then
          echo 'Error: xdebug.mode should not be set in CI. Have you committed xdebug config by accident? Check devbox.d/php/php.ini'
          exit 1
        fi

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm i
