docker-compose-yaml: docker-compose.yml

project: 'silverback-template'

tasks:
  post-rollout:
    - run:
        name: Install Drupal if necessary
        command: |
          if [[ $LAGOON_GIT_SAFE_BRANCH = lagoon-* ]] && ! drush status --fields=bootstrap | grep -q "Successful"; then
            drush si minimal -y --existing-config --account-name admin --account-pass admin
            drush php-script web/modules/custom/test_content/import.php
          fi
        service: cli
    - run:
        name: Run Drupal deploy tasks
        command: drush -y deploy
        service: cli
    - run:
        name: import translations from the ui
        command: drush scr scripts/translations-import.php
        service: cli
environments:
  dev:
    routes:
      - nginx:
          - example.cms.amazeelabs.dev
      - build:
          - example.build.amazeelabs.dev
    cronjobs:
      - name: drush cron
        schedule: '*/15 * * * *'
        command: drush cron
        service: cli
