[dev]
  autoLaunch = false

[functions]
  directory = "netlify/functions"

[build]
  edge_functions = "netlify/edge-functions"

[functions.strangler]
  included_files = ["public/404.html"]

[[edge_functions]]
  path = "/"
  function = "homepage-redirect"

[[edge_functions]]
  path = "/admin/_github/*"
  function = "github-proxy-auth"
