[dev]
  autoLaunch = false

[functions]
  directory = "netlify/functions"

[functions.strangler]
  included_files = ["public/404.html"]

[[edge_functions]]
  path = "/"
  function = "homepage-redirect"

