name: Deploy
on:
  workflow_dispatch:
jobs:
  test:
    name: Deploy to prod
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: stage

      - name: Merge stage -> prod
        uses: devmasx/merge-branch@1.4.0
        with:
          type: now
          target_branch: prod
          github_token: ${{ github.token }}