name: Tag release

on:
  push:
    branches:
      - 'prod'
  workflow_dispatch:

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d/%H/%M/%S')"
      - name: Checkout branch "prod"
        uses: actions/checkout@v4
        with:
          ref: prod
      - name: Create Git tag for PR
        uses: actions/github-script@v7
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{steps.date.outputs.date}}",
              sha: context.sha
            })
