name: Test
on:
  push:
env:
  # On Github Actions, use 127.0.0.1 instead of localhost, since this
  # works more reliably there.
  DRUPAL_INTERNAL_URL: 'http://127.0.0.1:8888'
  DRUPAL_EXTERNAL_URL: 'http://127.0.0.1:8888'
  PUBLISHER_URL: 'http://127.0.0.1:8000'
  NETLIFY_URL: 'http://127.0.0.1:8000'
  PLAYWRIGHT_WEBSITE_URL: 'http://127.0.0.1:8000'
  PLAYWRIGHT_CMS_URL: 'http://127.0.0.1:8888'

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          server-token: "local"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: pnpm turbo:test
        env:
          TURBO_API: 'http://127.0.0.1:9080'
          TURBO_TOKEN: 'local'
          TURBO_TEAM: 'local'

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: tests/e2e/playwright-report/
          retention-days: 3

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: packages/ui/storybook-static
          storybookBaseDir: packages/ui
          onlyChanged: true
          exitOnceUploaded: true

      - name: Deploy storybook to netlify
        run: npx netlify-cli deploy --prod --dir=packages/ui/storybook-static
        env:
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_STORYBOOK_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        if: ${{ github.ref  == 'refs/heads/dev' && vars.NETLIFY_STORYBOOK_ID != '' }}

  docker_build:
    name: Docker Build
    if: startsWith(github.head_ref, 'test-all/')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2
          bundler-cache: true
      - name: Install Pygmy
        run: gem install pygmy
      - name: Start Pygmy
        run: pygmy up
      - name: Docker Build
        run: DOCKER_BUILDKIT=1 docker-compose build
