name: Test without Turbo cache
on:
  workflow_dispatch:

jobs:

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        run: pnpm turbo:test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: tests/e2e/playwright-report/
          retention-days: 3

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: packages/ui/storybook-static
          storybookBaseDir: packages/ui
          onlyChanged: true
          exitOnceUploaded: true

      - name: Deploy storybook to netlify
        run: npx netlify-cli deploy --prod --dir=packages/ui/storybook-static
        env:
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_STORYBOOK_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        if: ${{ github.ref  == 'refs/heads/dev' && vars.NETLIFY_STORYBOOK_ID != '' }}

  docker_build:
    name: Docker Build
    if: startsWith(github.ref_name, 'test-all/')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2
          bundler-cache: true
      - name: Install Pygmy
        run: gem install pygmy
      - name: Start Pygmy
        run: pygmy up
      - name: Docker Build
        run: DOCKER_BUILDKIT=1 docker-compose build
