name: Test
on:
  push:
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          server-token: "local"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: pnpm test
        env:
          TURBO_API: 'http://127.0.0.1:9080'
          TURBO_TOKEN: "local"
          TURBO_TEAM: 'local'

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: packages/ui/storybook-static
          storybookBaseDir: packages/ui
          onlyChanged: true
          exitOnceUploaded: true
