name: Test Publisher
on:
  workflow_dispatch:
    inputs:
      env_vars:
        description: Environment variables
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Publisher
        uses: AmazeeLabs/publisher@d5704e30c4f6c341fcbe60cb66b458d9f27b8bb6
        with:
          env_vars: ${{ inputs.env_vars }}

      - name: Check env vars
        run: env

      - name: Check $DRUPAL_URL
        run: echo "$DRUPAL_URL"

      - name: Check $DRUPAL_URL secrets
        run: echo "$DRUPAL_URL" | awk -F'[//@]' '{print $1, $2, $3, $4}'
