name: Test Publisher
on:
  workflow_dispatch:
    inputs:
      env_vars:
        description: Environment variables
        required: true
        type: string

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Publisher
        uses: AmazeeLabs/publisher
        with:
          env_vars: ${{ inputs.env_vars }}

      - name: Check env vars
        run: env
